

const FlightList = [
    {
        id:1,
        FromPlace: 'MUM',
        ToPlace  : 'PUN',
        Airlines : 'Indigo Air',
        Logo : '/assets2/Indigo_Air_Logo.jpeg',
        FlightCode : 'IND-12',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Business',
        Fare     : 9500.00,
        Frequency : 'Weekly'
    },
    {
        id:2,
        FromPlace: 'MUM',
        ToPlace  : 'GOA',
        Airlines : 'Air India',
        Logo:'/assets2/Air_India_Logo.jpeg',
        FlightCode : 'AIR-101',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Business',
        Fare     : 2100.00,
        Frequency : 'Weekly'
    },
    {
        id:3,
        FromPlace: 'DEL',
        ToPlace  : 'PUN',
        Airlines : 'Go Air',
        Logo:'/assets2/Go_Air_Logo.jpeg',
        FlightCode : 'GO-01',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'First Class',
        Fare     : 3500.00,
        Frequency : 'Sunday'
    },
    {
        id:4,
        FromPlace: 'CHE',
        ToPlace  : 'BLR',
        Airlines : 'Air Vistara',
        // Logo : '/Images/Vistara_Logo.jpeg',
        Logo:'/assets2/Vistara_Logo.jpeg',
        FlightCode : 'VIS-99',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Economy',
        Fare     : 4000.00,
        Frequency : 'Daily'
    },
    {
        id:5,
        FromPlace: 'BLR',
        ToPlace  : 'PUN',
        Airlines : 'Jet Air',
        Logo:'/assets2/Jet_Airways_Logo.jpeg',
        FlightCode : 'JET-34',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Economy',
        Fare     : 3500.00,
        Frequency : 'Monthly'
    },
    {
        id:6,
        FromPlace: 'MUM',
        ToPlace  : 'CON',
        Airlines : 'Indigo Air',
        Logo:'/assets2/Indigo_Air_Logo.jpeg',
        FlightCode : 'IND-33',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'First Class',
        Fare     : 3500.00,
        Frequency : 'Daily'
    },
    {
        id:7,
        FromPlace: 'MUM',
        ToPlace  : 'KOL',
        Airlines : 'Kingfisher Airlines',
        Logo:'/assets2/Kingfisher_Logo.jpeg',
        FlightCode : 'KIN-66',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Economy',
        Fare     : 6500.00,
        Frequency : 'Weekly'
    },
    {
        id:8,
        FromPlace: 'BAN',
        ToPlace  : 'GOA',
        Airlines : 'Jet Air',
        Logo : '/assets2/Jet_Airways_Logo.jpeg',
        FlightCode : 'JET-44',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Business',
        Fare     : 3500.00,
        Frequency : 'Daily'
    },
    {
        id:9,
        FromPlace: 'LUC',
        ToPlace  : 'KOL',
        Airlines : 'Air Vistara',
        Logo : '/assets2/Vistara_Logo.jpeg',
        FlightCode : 'VIS-22',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Economy',
        Fare     : 5500.00,
        Frequency : 'Daily'
    },
    {
        id:10,
        FromPlace: 'IND',
        ToPlace  : 'PUN',
        Airlines : 'Air India',
        Logo : '/assets2/Air_India_Logo.jpeg',
        FlightCode : 'AIR-88',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Economy',
        Fare     : 3500.00,
        Frequency : 'Daily'
    },
    {
        id:11,
        FromPlace: 'MUM',
        ToPlace  : 'PUN',
        Airlines : 'Kingfisher Airlines',
        Logo : '/assets2/Kingfisher_Logo.jpeg',
        FlightCode : 'KIN-55',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'First Class',
        Fare     : 1200.00,
        Frequency : 'Daily'
    },
    {
        id:12,
        FromPlace: 'KOL',
        ToPlace  : 'GOA',
        Airlines : 'Air Vistara',
        Logo : '/assets2/Vistara_Logo.jpeg',
        FlightCode : 'VIS-01',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Economy',
        Fare     : 3800.00,
        Frequency : 'Daily'
    },
    {
        id:13,
        FromPlace: 'PUN',
        ToPlace  : 'GOA',
        Airlines : 'Jet Air',
        Logo : '/assets2/Jet_Airways_Logo.jpeg',
        FlightCode : 'JET-201',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Business',
        Fare     : 8500.00,
        Frequency : 'Sunday'
    },
    {
        id:14,
        FromPlace: 'MUM',
        ToPlace  : 'IND',
        Airlines : 'Indigo Air',
        Logo : '/assets2/Indigo_Air_Logo.jpeg',
        FlightCode : 'IND-701',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Economy',
        Fare     : 3000.00,
        Frequency : 'Daily'
    },
    {
        id:15,
        FromPlace: 'PUN',
        ToPlace  : 'LUC',
        Airlines : 'Jet Air',
        Logo : '/assets2/Jet_Airways_Logo.jpeg',
        FlightCode : 'JET-301',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'First Class',
        Fare     : 3500.00,
        Frequency : 'Daily'
    },
    {
        id:16,
        FromPlace: 'GOA',
        ToPlace  : 'LUC',
        Airlines : 'Indigo Air',
        Logo : '/assets2/Indigo_Air_Logo.jpeg',
        FlightCode : 'IND-78',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Economy',
        Fare     : 3500.00,
        Frequency : 'Daily'
    },
    {
        id:17,
        FromPlace: 'BLR',
        ToPlace  : 'JAM',
        Airlines : 'Indigo Air',
        Logo : '/assets2/Indigo_Air_Logo.jpeg',
        FlightCode : 'IND-50',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Business',
        Fare     : 6700.00,
        Frequency : 'Daily'
    },
    {
        id:18,
        FromPlace: 'JAM',
        ToPlace  : 'CON',
        Airlines : 'Air Vistara',
        Logo : '/assets2/Vistara_Logo.jpeg',
        FlightCode : 'VIS-90',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Economy',
        Fare     : 3500.00,
        Frequency : 'Daily'
    },
    {
        id:19,
        FromPlace: 'PUN',
        ToPlace  : 'MUM',
        Airlines : 'Indigo Air',
        Logo : '/assets2/Indigo_Air_Logo.jpeg',
        FlightCode : 'IND-20',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Economy',
        Fare     : 3200.00,
        Frequency : 'Weekly'
    },
    {
        id:20,
        FromPlace: 'PUN',
        ToPlace  : 'JAM',
        Airlines : 'Indigo Air',
        Logo : '/assets2/Indigo_Air_Logo.jpeg',
        FlightCode : 'IND-10',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Business',
        Fare     : 3500.00,
        Frequency : 'Daily'
    },
    {
        id:21,
        FromPlace: 'PUN',
        ToPlace  : 'IND',
        Airlines : 'Kingfisher Airlines',
        Logo : '/assets2/Kingfisher_Logo.jpeg',
        FlightCode : 'KIN-05',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'First Class',
        Fare     : 7500.00,
        Frequency : 'Daily'
    },
    {
        id:22,
        FromPlace: 'MUM',
        ToPlace  : 'PUN',
        Airlines : 'Jet Air',
        Logo : '/assets2/Jet_Airways_Logo.jpeg',
        FlightCode : 'JET-100',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Economy',
        Fare     : 3500.00,
        Frequency : 'Daily'
    },
    {
        id:23,
        FromPlace: 'KOL',
        ToPlace  : 'PUN',
        Airlines : 'Air India',
        Logo : '/assets2/Air_India_Logo.jpeg',
        FlightCode : 'AIR-501',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'Business',
        Fare     : 5900.00,
        Frequency : 'Sunday'
    },
    {
        id:24,
        FromPlace: 'MUM',
        ToPlace  : 'LUC',
        Airlines : 'Air Vistara',
        Logo : '/assets2/Vistara_Logo.jpeg',
        FlightCode : 'VIS-56',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'First Class',
        Fare     : 3800.00,
        Frequency : 'Weekly'
    },
    {
        id:25,
        FromPlace: 'MUM',
        ToPlace  : 'KOL',
        Airlines : 'GO Air',
        Logo : '/assets2/Indigo_Air_Logo.jpeg',
        FlightCode : 'GO-09',
        StartTime: '04:30',
        EndTime  : '06:00',
        Class    : 'First Class',
        Fare     : 6900.00,
        Frequency : 'Daily'
    }
]

export default FlightList;